export { default as Start } from "./Start/Start";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as Search } from "./Search/Search";
export { default as ListHotel } from "./ListHotel/ListHotel";
export { default as PersonalDetails } from "./PersonalDetails/PersonalDetails";
export { default as EditProfile } from "./EditProfile/EditProfile";
export { default as ChangePassword } from "./ChangePassword/ChangePassword";
export { default as Support } from "./Support/Support";