export { default as Start } from './Start/Start'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as ListHotel } from './ListHotel/ListHotel'
export { default as Search } from './Search/Search'